
full_stack_developer_keywords = [
    'AngularJS',
    'React.js',
    'HTML5',
    'Cascading Style Sheets (CSS)',
    'JavaScript',
    'Java',
    'Python',
    'PHP',
    'Node.js',
    'MySQL',
    'SQL',
    'MongoDB',
    'jQuery',
    'Git',
    'GitHub',
    'BitBucket'
    'AJAX',
    'Laravel',
    'HTML',
    'Bootstrap',
    'TypeScript',
    'Amazon Web Services (AWS)',
    'Docker Products',
    'Rest API',
    'Unit Testing',
    'Vue.js',
    'Ruby on Rails',
    'Express.js',
    'Redux',
    'Django',
    'Flask',
    'Spring Boot',
    'JSON',
    'MaterialUI',
    'XML',
    'HTTP',
    'Redis'
]

